#include<stdio.h>
main()
{
	char ch;
	printf ("Enterthe letter :");
	ch =getchar();
	switch(ch)
	{
		case'A': printf("Alpha");
		           break;
		case'a': printf("Alpha");
		           break;
		case'B': printf("Bravo");
		           break;
		case'b': printf("Bravo");
		           break;
		case'C': printf("Charlie");
		           break;
		case'c': printf("Charlie");
		           break;
		case'D': printf("Delta");
		           break;
		case'd': printf("Delta");
		           break;
		case'E': printf("Echo");
		           break;
		case'e': printf("Echo");
		           break;  
		case'F': printf("Foxtrot");
		           break;
		case'f': printf("Foxtrot");
		           break;
		case'G': printf("Golf");
		           break;
		case'g': printf("Golf");
		           break;
		case'H': printf("Hotel");
		           break;
		case'h': printf("Hotel");
		           break;
		case'I': printf("Indie");
		           break;
		case'i': printf("Indie");
		           break;
		case'J': printf("Juliett");
		           break;
		case'j': printf("Juliett");
		           break; 
		case'K': printf("Kilo");
		           break;
		case'k': printf("Kilo");
		           break;
		case'L': printf("Lima");
		           break;
		case'l': printf("Lima");
		           break;
		case'M': printf("Mike");
		           break;
		case'm': printf("Mike");
		           break;
		case'N': printf("November");
		           break;
		case'n': printf("November");
		           break;
		case'O': printf("Oscar");
		           break;
		case'o': printf("Oscar");
		           break;  
		case'P': printf("Papa");
		           break;
		case'p': printf("Papa");
		           break;
		case'Q': printf("Quebec");
		           break;
		case'q': printf("Quebec");
		           break;
		case'R': printf("Romeo");
		           break;
		case'r': printf("Romeo");
		           break;
		case'S': printf("Sierra");
		           break;
		case's': printf("Sierra");
		           break;
		case'T': printf("Tango");
		           break;
		case't': printf("Tango");
		           break; 		               
		case'U': printf("Uniform");
		           break;
		case'u': printf("Uniform");
		           break;  
		case'V': printf("Victor");
		           break;
		case'v': printf("Victor");
		           break;
		case'W': printf("Whiskey");
		           break;
		case'w': printf("Whiskey");
		           break;
		case'X': printf("X-ray");
		           break;
		case'x': printf("X-ray");
		           break;
		case'Y': printf("Yankee");
		           break;
		case'y': printf("Yankee");
		           break;
		case'Z': printf("Zulu");
		           break;
		case'z': printf("Zulu");
		           break; 		               			            
	default:
	printf ("is a consonant");	           	
	}
}
